### ISSUE TITLE
Cancelling orders related to issue #5

### ISSUE THREAD

**Issue by kirkyb** [XRPL-Labs/offer-create-xapp#6]
I have 4 open sell orders that were created as outlined in issue #5 
Whenever I try to cancel any of them, the cancel order shows that it has been approved in Xumm, yet they still remain open in my order book/list (i.e. they cannot be cancelled)

**Comment by WietseWind** [comment]
How do you try to cancel? What are the steps taken?

**Comment by kirkyb** [comment]
Using the xApp I clicked on 'cancel order' for each of the orders and proceeded to approve each one. Regardless of which order I did it in, none cancelled even though numerous 'Cancel offer' attempts are listed in the events section in Xumm.
However I've checked my order book today and they are no longer there.

**Comment by WietseWind** [comment]
OK, so they were in fact cancelled but the xApp didn't reflect that? @KoenPaas

**Comment by kirkyb** [comment]
Correct, this appears to be the case.

**Comment by WietseWind** [comment]
Thanks, we're going to check it :)

**Comment by KoenPaas** [comment]
Bug is fixed thank you for the feedback

**Comment by kirkyb** [comment]
Hi Koen, I've just signed in to check this and have noticed now that buy orders aren't being added to the order book. Restarting the xApp and XUMM doesn't fix this.
